# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizaciones', '__first__'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfil', models.CharField(max_length=12, unique=True, verbose_name='Documento de identidad')),
                ('fk_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.TipoDocumento')),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_perfil',
                'ordering': ('fk_user',),
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserProfileVocero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_vocero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Vocero')),
            ],
            options={
                'db_table': 'users_perfil_vocero',
                'ordering': ('fk_user',),
                'verbose_name': 'Perfil de usuario vocero',
                'verbose_name_plural': 'Perfiles de usuarios voceros',
            },
        ),
    ]
