# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunaConsejoComunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Consejo Comunal asociado a Comuna',
                'ordering': ('fk_comuna',),
                'verbose_name_plural': 'Consejos Comunales asociados a las Comunas',
            },
        ),
        migrations.CreateModel(
            name='ComunaMovimientoSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Movimiento Social Relacionado a la Comuna',
                'ordering': ('fk_comuna',),
                'verbose_name_plural': 'Movimientos Sociales Relacionados a las Comunas',
            },
        ),
        migrations.CreateModel(
            name='ComunaOrgSociproductiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Organizacion Socioproductiva relacionada a la comuna',
                'ordering': ('fk_comuna',),
                'verbose_name_plural': 'Organizaciones Socioproductivas relacionadas a las comunas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Movimiento Social',
                'ordering': ('nombre',),
                'verbose_name_plural': 'Movimientos Sociales',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16)),
                ('rif', models.CharField(max_length=12, unique=True)),
                ('situr', models.CharField(max_length=17)),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=128)),
                ('fecha_conformacion', models.DateField()),
                ('sector', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fk_tipo_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.TipoOrganizacion')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Parroquia')),
            ],
            options={
                'verbose_name': 'Organizacion Social',
                'ordering': ('codigo',),
                'verbose_name_plural': 'Organizaciones Sociales',
            },
        ),
        migrations.CreateModel(
            name='Vocero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('documento_identidad', models.PositiveIntegerField()),
                ('sector', models.TextField(blank=True, null=True)),
                ('casa_edificio_calle', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=14, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fk_org_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.OrganizacionSocial')),
                ('fk_rol_unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.UnidadesOrganizacionSocial')),
                ('fk_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.TipoDocumento')),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Parroquia')),
            ],
            options={
                'verbose_name': 'Vocero',
                'ordering': ('documento_identidad',),
                'verbose_name_plural': 'Voceros',
            },
        ),
        migrations.CreateModel(
            name='VoceroComite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.ComiteUnidadEjecutiva')),
                ('fk_vocero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Vocero')),
            ],
            options={
                'verbose_name': 'Vocero del comite',
                'ordering': ('fk_vocero',),
                'verbose_name_plural': 'Voceros de los comites',
            },
        ),
        migrations.AddField(
            model_name='comunaorgsociproductiva',
            name='fk_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='organizaciones.OrganizacionSocial'),
        ),
        migrations.AddField(
            model_name='comunaorgsociproductiva',
            name='fk_ospc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opsc', to='organizaciones.OrganizacionSocial'),
        ),
        migrations.AddField(
            model_name='comunamovimientosocial',
            name='fk_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas_mov', to='organizaciones.OrganizacionSocial'),
        ),
        migrations.AddField(
            model_name='comunamovimientosocial',
            name='fk_mov_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.MovimientoSocial'),
        ),
        migrations.AddField(
            model_name='comunaconsejocomunal',
            name='fk_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna', to='organizaciones.OrganizacionSocial'),
        ),
        migrations.AddField(
            model_name='comunaconsejocomunal',
            name='fk_consejo_comunal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consejo_comunal', to='organizaciones.OrganizacionSocial'),
        ),
        migrations.AlterUniqueTogether(
            name='vocero',
            unique_together=set([('fk_org_social', 'documento_identidad')]),
        ),
        migrations.AlterUniqueTogether(
            name='comunaorgsociproductiva',
            unique_together=set([('fk_comuna', 'fk_ospc')]),
        ),
        migrations.AlterUniqueTogether(
            name='comunamovimientosocial',
            unique_together=set([('fk_comuna', 'fk_mov_social')]),
        ),
        migrations.AlterUniqueTogether(
            name='comunaconsejocomunal',
            unique_together=set([('fk_comuna', 'fk_consejo_comunal')]),
        ),
    ]
