# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Calidad de los Servicios',
                'ordering': ('estatus',),
                'verbose_name': 'Calidad del Servicio',
            },
        ),
        migrations.CreateModel(
            name='ComiteUnidadEjecutiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Comites de las Organizaciones Sociales',
                'ordering': ('tipo',),
                'verbose_name': 'Comite de la Organizacion Social',
            },
        ),
        migrations.CreateModel(
            name='CondicionVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiciones', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Condiciones de las Viviendas',
                'ordering': ('condiciones',),
                'verbose_name': 'Condicion de la Vivienda',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Representa (Latitud, Longitud)', srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'ordering': ('nombre',),
                'verbose_name': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civiles', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estado Civil',
                'ordering': ('estado_civiles',),
                'verbose_name': 'Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='EstadoVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados de las Viviendas',
                'ordering': ('estado',),
                'verbose_name': 'Estado de la Vivienda',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Representa (Latitud, Longitud)', srid=4326)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Estado')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ('nombre',),
                'verbose_name': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nacionalidades', models.CharField(max_length=128)),
                ('abreviatura', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ('tipo_nacionalidades',),
                'verbose_name': 'Nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Representa (Latitud, Longitud)', srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ('nombre',),
                'verbose_name': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentescos', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('parentescos',),
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Representa (Latitud, Longitud)', srid=4326)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Municipio')),
            ],
            options={
                'verbose_name_plural': 'Parroquias',
                'ordering': ('nombre',),
                'verbose_name': 'Parroquia',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(max_length=4, verbose_name='Acrónimo')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Tipos Documentos',
                'ordering': ('abreviatura',),
                'verbose_name': 'Tipo Documento',
            },
        ),
        migrations.CreateModel(
            name='TipoEnfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_enfermedades', models.CharField(max_length=500, unique=True)),
                ('causa', models.TextField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo Enfermedades',
                'ordering': ('tipo_enfermedades',),
                'verbose_name': 'Tipo Enfermedad',
            },
        ),
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('abreviatura', models.CharField(max_length=4, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Tipos de Organizaciones',
                'ordering': ('tipo',),
                'verbose_name': 'Tipo de Organizacion',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('tipos',),
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajos', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Trabajo',
                'ordering': ('tipo_trabajos',),
                'verbose_name': 'Tipo Trabajo',
            },
        ),
        migrations.CreateModel(
            name='UnidadesOrganizacionSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Unidades de los Organizaciones Sociales',
                'ordering': ('tipo',),
                'verbose_name': 'Unidad del la Organizacion Social',
            },
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='fk_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Pais'),
        ),
        migrations.AddField(
            model_name='comiteunidadejecutiva',
            name='fk_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.UnidadesOrganizacionSocial', verbose_name='Unidad Ejecutiva'),
        ),
    ]
